{% set name = "upolygon" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/v7labs/upolygon/archive/v{{ version }}.tar.gz
  sha256: 49ac5a6b79aa6986525f370d069303671517488aa7776f91933922a8d019a45e

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv  # [win]
  script: USE_CYTHON=true {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython  # [not win]
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  source_files:
    - tests
  imports:
    - upolygon
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - numpy

about:
  home: https://github.com/v7labs/upolygon
  summary: Collection of fast polygon operations for DL
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hajapy
    - simedw
