{% set name = "upolygon" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/v7labs/upolygon/archive/v{{ version }}.zip
  sha256: a21d874ef88b3599d19a3a22b215eed2c5e7abf2a06f5eff9fcc6da4516a4278

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv  # [win]
  script: USE_CYTHON=true {{ PYTHON }} -m pip install . -vv  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython  # [not win]
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy

test:
  source_files:
    - tests
  imports:
    - upolygon
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - numpy

about:
  home: https://github.com/v7labs/upolygon
  summary: Collection of fast polygon operations for DL
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hajapy
    - simedw
